export default {
  name: 'siteSettings',
  title: 'Cấu hình website',
  type: 'document',
  fields: [
    {
      name: 'logoMark',
      title: '1. Thiết kế biểu tượng logo',
      type: 'object',
      description: 'Chọn mẫu React an toàn và tinh chỉnh logo dùng chung cho Header, menu mobile và Footer. Không chạy code HTML/React nhập từ CMS.',
      initialValue: {
        template: 'zRhombus',
        letter: 'C',
        letterStyle: 'system',
        colorPreset: 'brandOrange',
        primaryColor: '#ea580c',
        textColor: '#ffffff',
        fillColor: '#0f172a',
        fillOpacity: 0.6,
        strokeWidth: 5,
        scalePercent: 100,
        glowEnabled: true,
        glowColor: '#f97316',
        glowOpacity: 0.2,
        glowBlur: 'medium',
        shineEnabled: false,
        animationEnabled: true,
        shapeHoverRotate: 180,
        letterHoverRotate: 0,
        springStiffness: 400,
        springDamping: 30,
      },
      fieldsets: [
        { name: 'design', title: 'Mẫu và ký tự', options: { collapsible: true, collapsed: false } },
        { name: 'colors', title: 'Màu sắc và đường nét', options: { collapsible: true, collapsed: false } },
        { name: 'effects', title: 'Glow và ánh sáng', options: { collapsible: true, collapsed: true } },
        { name: 'motion', title: 'Chuyển động khi hover', options: { collapsible: true, collapsed: true } },
      ],
      fields: [
        {
          name: 'template',
          title: 'Mẫu thiết kế',
          type: 'string',
          initialValue: 'zRhombus',
          fieldset: 'design',
          options: {
            list: [
              { title: 'Hình thoi đặc', value: 'zRhombus' },
              { title: 'Lục giác viền', value: 'zHexagon' },
            ],
            layout: 'radio',
          },
          validation: (Rule: any) => Rule.required(),
        },
        {
          name: 'letter',
          title: 'Ký tự trong logo',
          type: 'string',
          fieldset: 'design',
          description: 'Nhập 1–2 ký tự đại diện thương hiệu. Ví dụ: C, A, TX.',
          validation: (Rule: any) => Rule.max(2),
        },
        {
          name: 'letterStyle',
          title: 'Kiểu chữ trong biểu tượng',
          type: 'string',
          fieldset: 'design',
          initialValue: 'system',
          options: {
            list: [
              { title: 'Font hệ thống đậm', value: 'system' },
              { title: 'Vector Z cân bằng', value: 'vectorZ' },
              { title: 'Serif thương hiệu', value: 'serif' },
              { title: 'Mono kỹ thuật', value: 'mono' },
            ],
          },
        },
        {
          name: 'scalePercent',
          title: 'Tỷ lệ biểu tượng (%)',
          type: 'number',
          fieldset: 'design',
          description: 'Giới hạn an toàn 80–115% để không phá bố cục Header/Footer.',
          initialValue: 100,
          validation: (Rule: any) => Rule.min(80).max(115).integer(),
        },
        {
          name: 'colorPreset',
          title: 'Bộ màu nhanh',
          type: 'string',
          fieldset: 'colors',
          initialValue: 'brandOrange',
          options: {
            list: [
              { title: 'Brand Orange', value: 'brandOrange' },
              { title: 'Cyber Cyan', value: 'cyberCyan' },
              { title: 'Neon Purple', value: 'neonPurple' },
              { title: 'Laser Emerald', value: 'emerald' },
              { title: 'Titanium Gold', value: 'titaniumGold' },
              { title: 'Crimson Red', value: 'crimson' },
              { title: 'Tự chọn màu', value: 'custom' },
            ],
          },
        },
        {
          name: 'primaryColor',
          title: 'Màu khối / màu viền',
          type: 'string',
          fieldset: 'colors',
          description: 'Hình thoi: màu nền. Lục giác: màu đường viền.',
          hidden: ({ parent }: any) => parent?.colorPreset !== 'custom',
          validation: (Rule: any) => Rule.regex(/^#[0-9a-fA-F]{6}$/, { name: 'hex color' }),
        },
        {
          name: 'textColor',
          title: 'Màu ký tự',
          type: 'string',
          fieldset: 'colors',
          hidden: ({ parent }: any) => parent?.colorPreset !== 'custom',
          validation: (Rule: any) => Rule.regex(/^#[0-9a-fA-F]{6}$/, { name: 'hex color' }),
        },
        {
          name: 'fillColor',
          title: 'Màu nền bên trong lục giác',
          type: 'string',
          fieldset: 'colors',
          hidden: ({ parent }: any) => parent?.template !== 'zHexagon' || parent?.colorPreset !== 'custom',
          validation: (Rule: any) => Rule.regex(/^#[0-9a-fA-F]{6}$/, { name: 'hex color' }),
        },
        {
          name: 'fillOpacity',
          title: 'Độ trong nền lục giác',
          type: 'number',
          fieldset: 'colors',
          description: '0 = trong suốt, 1 = đặc hoàn toàn.',
          initialValue: 0.6,
          hidden: ({ parent }: any) => parent?.template !== 'zHexagon',
          validation: (Rule: any) => Rule.min(0).max(1),
        },
        {
          name: 'strokeWidth',
          title: 'Độ dày viền lục giác',
          type: 'number',
          fieldset: 'colors',
          initialValue: 5,
          hidden: ({ parent }: any) => parent?.template !== 'zHexagon',
          validation: (Rule: any) => Rule.min(1).max(10),
        },
        { name: 'glowEnabled', title: 'Bật hiệu ứng glow', type: 'boolean', fieldset: 'effects', initialValue: true },
        {
          name: 'glowColor',
          title: 'Màu glow riêng',
          type: 'string',
          fieldset: 'effects',
          hidden: ({ parent }: any) => parent?.glowEnabled === false || parent?.colorPreset !== 'custom',
          validation: (Rule: any) => Rule.regex(/^#[0-9a-fA-F]{6}$/, { name: 'hex color' }),
        },
        {
          name: 'glowOpacity',
          title: 'Độ sáng glow',
          type: 'number',
          fieldset: 'effects',
          description: 'Từ 0 đến 0.8. Mặc định 0.2.',
          initialValue: 0.2,
          hidden: ({ parent }: any) => parent?.glowEnabled === false,
          validation: (Rule: any) => Rule.min(0).max(0.8),
        },
        {
          name: 'glowBlur',
          title: 'Độ tỏa glow',
          type: 'string',
          fieldset: 'effects',
          initialValue: 'medium',
          hidden: ({ parent }: any) => parent?.glowEnabled === false,
          options: {
            list: [
              { title: 'Nhẹ', value: 'soft' },
              { title: 'Vừa', value: 'medium' },
              { title: 'Mạnh', value: 'strong' },
            ],
            layout: 'radio',
          },
        },
        { name: 'shineEnabled', title: 'Bật vệt sáng quét khi hover', type: 'boolean', fieldset: 'effects', initialValue: false },
        { name: 'animationEnabled', title: 'Bật chuyển động khi hover', type: 'boolean', fieldset: 'motion', initialValue: true },
        {
          name: 'shapeHoverRotate',
          title: 'Góc xoay khung',
          type: 'number',
          fieldset: 'motion',
          description: 'Độ, từ -360 đến 360. Mặc định 180°.',
          initialValue: 180,
          hidden: ({ parent }: any) => parent?.animationEnabled === false,
          validation: (Rule: any) => Rule.min(-360).max(360),
        },
        {
          name: 'letterHoverRotate',
          title: 'Góc xoay ký tự',
          type: 'number',
          fieldset: 'motion',
          description: 'Độ xoay ký tự khi hover. Mặc định 0°.',
          initialValue: 0,
          hidden: ({ parent }: any) => parent?.animationEnabled === false,
          validation: (Rule: any) => Rule.min(-180).max(180),
        },
        {
          name: 'springStiffness',
          title: 'Độ cứng chuyển động',
          type: 'number',
          fieldset: 'motion',
          initialValue: 400,
          hidden: ({ parent }: any) => parent?.animationEnabled === false,
          validation: (Rule: any) => Rule.min(100).max(800).integer(),
        },
        {
          name: 'springDamping',
          title: 'Độ giảm chấn',
          type: 'number',
          fieldset: 'motion',
          initialValue: 30,
          hidden: ({ parent }: any) => parent?.animationEnabled === false,
          validation: (Rule: any) => Rule.min(10).max(80).integer(),
        },
      ],
      options: {
        collapsible: true,
        collapsed: false,
      },
    },
    {
      name: 'logoWordmark',
      title: '2. Chữ logo',
      type: 'object',
      description: 'Quản lý tên thương hiệu và dòng mô tả. Dữ liệu này được dùng chung cho Header, Footer và SEO.',
      initialValue: {
        primaryText: 'COMPANY',
        accentText: '',
        tagline: {
          vi: 'Giải pháp kỹ thuật',
          en: 'Engineering Solutions',
          jp: 'エンジニアリングソリューション',
          kr: '엔지니어링 솔루션',
          cn: '工程解决方案',
        },
      },
      fields: [
        {
          name: 'primaryText',
          title: 'Phần chữ chính',
          type: 'string',
          description: 'Nhập phần chính của tên thương hiệu.',
          validation: (Rule: any) => Rule.max(20),
        },
        {
          name: 'accentText',
          title: 'Phần chữ nhấn màu',
          type: 'string',
          description: 'Không bắt buộc. Dùng khi muốn tách một phần tên thương hiệu bằng màu nhấn.',
          validation: (Rule: any) => Rule.max(20),
        },
        {
          name: 'tagline',
          title: 'Dòng mô tả theo ngôn ngữ',
          type: 'object',
          fields: [
            { name: 'vi', title: 'Tiếng Việt', type: 'string', description: 'Ví dụ: Giải pháp kỹ thuật' },
            { name: 'en', title: 'English', type: 'string', description: 'Example: Engineering Solutions' },
            { name: 'jp', title: '日本語', type: 'string', description: '例: エンジニアリングソリューション' },
            { name: 'kr', title: '한국어', type: 'string', description: '예: 엔지니어링 솔루션' },
            { name: 'cn', title: '中文', type: 'string', description: '示例：工程解决方案' },
          ],
        },
      ],
      options: {
        collapsible: true,
        collapsed: false,
      },
    },
    {
      name: 'phoneDisplay',
      title: 'Số điện thoại hiển thị',
      type: 'string',
      description: 'Ví dụ: +84 28 1234 5678. Số này sẽ hiển thị trên toàn website.',
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'phoneTel',
      title: 'Số điện thoại dùng để gọi',
      type: 'string',
      description: 'Chỉ nhập số và dấu +, ví dụ: +842812345678.',
      validation: (Rule: any) => Rule.required(),
    },
    { name: 'zaloNumber', title: 'Số Zalo', type: 'string', description: 'Không bắt buộc. Dùng để tạo link zalo.me.' },
    { name: 'email', title: 'Email liên hệ', type: 'string' },
    {
      name: 'addressDisplay',
      title: 'Địa chỉ hiển thị',
      type: 'string',
      description: 'Địa chỉ mặc định dùng ở Footer và dữ liệu SEO. Địa điểm chi tiết được quản lý trong mục Địa điểm.',
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'googleMapsUrl',
      title: 'Liên kết Google Maps',
      type: 'url',
      description: 'Link Google Maps mặc định. Các địa điểm riêng có thể dùng link riêng trong mục Địa điểm.',
      validation: (Rule: any) => Rule.uri({ scheme: ['http', 'https'] }),
    },
    {
      name: 'googleRating',
      title: 'Điểm đánh giá Google',
      type: 'number',
      description: 'Trường tương thích dữ liệu cũ. Nên quản lý trong mục Đánh giá Google.',
      validation: (Rule: any) => Rule.min(0).max(5),
    },
    {
      name: 'googleReviewCount',
      title: 'Tổng số đánh giá Google',
      type: 'number',
      description: 'Trường tương thích dữ liệu cũ. Nên quản lý trong mục Đánh giá Google.',
      validation: (Rule: any) => Rule.min(0).integer(),
    },
    {
      name: 'googleReviews',
      title: 'Đánh giá Google cũ',
      type: 'array',
      description: 'Chỉ giữ để tương thích dữ liệu cũ. Đánh giá mới nên quản lý trong mục Đánh giá Google.',
      of: [
        {
          type: 'object',
          name: 'googleReview',
          title: 'Đánh giá Google',
          fields: [
            {
              name: 'author',
              title: 'Tên người đánh giá',
              type: 'string',
              validation: (Rule: any) => Rule.required(),
            },
            {
              name: 'rating',
              title: 'Số sao',
              type: 'number',
              initialValue: 5,
              validation: (Rule: any) => Rule.required().min(1).max(5).integer(),
            },
            {
              name: 'content',
              title: 'Nội dung đánh giá',
              type: 'text',
              rows: 4,
              validation: (Rule: any) => Rule.required(),
            },
            {
              name: 'meta',
              title: 'Ghi chú',
              type: 'string',
            },
            {
              name: 'reviewUrl',
              title: 'Link đánh giá trên Google',
              type: 'url',
              validation: (Rule: any) => Rule.uri({ scheme: ['http', 'https'] }),
            },
          ],
          preview: {
            select: { title: 'author', subtitle: 'content' },
          },
        },
      ],
    },
    { name: 'wechatId', title: 'WeChat ID', type: 'string' },
    { name: 'wechatUrl', title: 'WeChat URL', type: 'url', validation: (Rule: any) => Rule.uri({ scheme: ['http', 'https'] }) },
    { name: 'lineUrl', title: 'LINE URL', type: 'url', validation: (Rule: any) => Rule.uri({ scheme: ['http', 'https'] }) },
    { name: 'facebookUrl', title: 'Facebook URL', type: 'url', validation: (Rule: any) => Rule.uri({ scheme: ['http', 'https'] }) },
    { name: 'youtubeUrl', title: 'YouTube URL', type: 'url', validation: (Rule: any) => Rule.uri({ scheme: ['http', 'https'] }) },
    { name: 'tiktokUrl', title: 'TikTok URL', type: 'url', validation: (Rule: any) => Rule.uri({ scheme: ['http', 'https'] }) },
    { name: 'twitterUrl', title: 'X / Twitter URL', type: 'url', validation: (Rule: any) => Rule.uri({ scheme: ['http', 'https'] }) },
  ],
  preview: {
    prepare() {
      return { title: 'Cấu hình toàn website' }
    },
  },
}
